language: cpp
sudo: required
dist: trusty

compiler:
  - clang

addons:
  apt:
    sources:
      # Boost 1.58
      - sourceline: ppa:kzemek/boost
    packages:
      - libboost1.58-dev

matrix:
  include:
    - os: osx

before_install:
  - ./travis/build_prereq.sh
  - export OMPI_CC=${CC}
  - export OMPI_CXX=${CXX}

branches:
  only:
    - master
    - travis # To debug .travis.yml

install: true

script:
  # Stop on first error
  - set -e
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)" # work around for a bug in Travis CI https://github.com/travis-ci/travis-ci/issues/8920

  # Create directory for installed prerequisites
  - export PREREQS_DIR=$(./travis/full_path.sh $TRAVIS_BUILD_DIR/../installed)
  - echo $PREREQS_DIR
  - mkdir $PREREQS_DIR
  - ls $TRAVIS_BUILD_DIR/..
  # Install TRIQS wo tests
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/TRIQS/triqs.git triqs.git && pushd triqs.git
  - git checkout 1.4.x && pushd
  - mkdir triqs.build && pushd triqs.build
  - |
    cmake ../triqs.git \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR/triqs \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DBuild_Documentation=OFF \
    -DBuild_Tests=OFF
  - make -j3 install

  # Install ALPSCore wo tests
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/ALPSCore/ALPSCore.git ALPSCore.git
  - mkdir ALPSCore.build && pushd ALPSCore.build
  - |
    cmake ../ALPSCore.git                                 \
    -DCMAKE_CXX_COMPILER=mpic++                           \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR/ALPSCore          \
    -DALPS_INSTALL_EIGEN=true                             \
    -DTesting=false                                       \
    -DDocumentation=OFF                                   \
    -DALPS_CXX_STD=c++14                                  \
    -DENABLE_MPI=ON
  - make -j3
  - make install
  - export ALPSCore_DIR=$PREREQS_DIR/ALPSCore
   
  # Build and install ALPSCore/CT-HYB
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/ALPSCore/CT-HYB.git CT-HYB.git
  - mkdir CT-HYB.build
  - cd CT-HYB.build
  - |
    cmake ../CT-HYB.git                                   \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_CXX_FLAGS='-DALPS_GF_DEBUG'                   \
    -DCMAKE_CXX_COMPILER=mpic++                           \
    -DCMAKE_INSTALL_PREFIX=$PREREQS_DIR/CT-HYB
  - make -j3
  - make install
  - export ALPSCoreCTHYB_DIR=$PREREQS_DIR/CT-HYB

  # Build, test and install triqs_interface
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/shinaoka/triqs_interface.git triqs_interface.git
  - mkdir triqs_interface.build
  - cd triqs_interface.build
  - |
    cmake ../triqs_interface.git                          \
    -DCMAKE_BUILD_TYPE=Debug                              \
    -DCMAKE_CXX_FLAGS='-DALPS_GF_DEBUG'                   \
    -DCMAKE_CXX_COMPILER=mpic++                           \
    -DTRIQS_PATH=$PREREQS_DIR/triqs
  - make -j3
  - make install

